# Generated by Django 3.2.15 on 2022-08-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(max_length=100)),
                ('pokemon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonsite.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=100)),
                ('pokemon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonsite.pokemon')),
            ],
        ),
    ]
