# Generated by Django 3.2.15 on 2022-08-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonsite', '0002_auto_20220811_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('pokemon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonsite.pokemon')),
            ],
        ),
    ]
