# Generated by Django 3.2.15 on 2022-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonsite', '0003_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
