# Generated by Django 3.2.15 on 2022-08-12 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonsite', '0007_auto_20220811_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='pokemon_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='pokemonsite.pokemon'),
        ),
    ]
