# Generated by Django 3.2.15 on 2022-08-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonsite', '0008_alter_ability_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(default='www.empty.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='pokemon_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='pokemonsite.pokemon'),
        ),
    ]
